-- ============================================================
-- KisanAI v2.0 — Complete Supabase Schema
-- Run this in your Supabase SQL editor
-- ============================================================

-- 1. Profiles (extended)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT,
  phone TEXT UNIQUE,
  location TEXT,
  avatar TEXT DEFAULT '👨‍🌾',
  role TEXT DEFAULT 'Farmer',
  acres NUMERIC DEFAULT 0,
  soil_type TEXT DEFAULT 'loamy',
  joined TIMESTAMP WITH TIME ZONE DEFAULT now(),
  last_active TIMESTAMP WITH TIME ZONE DEFAULT now(),
  points INTEGER DEFAULT 10,
  level INTEGER DEFAULT 1,
  lang TEXT DEFAULT 'en'
);

-- 2. AI Crop Scans
CREATE TABLE IF NOT EXISTS scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  crop_name TEXT,
  image_url TEXT,
  finding TEXT,
  confidence NUMERIC,
  severity TEXT CHECK (severity IN ('none', 'medium', 'high')),
  treatment TEXT,
  growth_stage TEXT,
  days_to_harvest INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Marketplace Products
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT CHECK (category IN ('Seeds', 'Fertilizer', 'Pesticide', 'Tools', 'Equipment')),
  price NUMERIC NOT NULL,
  unit TEXT,
  stock INTEGER DEFAULT 0,
  seller TEXT,
  description TEXT,
  rating NUMERIC DEFAULT 0,
  tag TEXT
);

-- 4. Orders
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  items JSONB,
  total NUMERIC,
  status TEXT CHECK (status IN ('processing', 'shipped', 'delivered', 'cancelled')) DEFAULT 'processing',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. Farm Crops Tracker
CREATE TABLE IF NOT EXISTS farm_crops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  crop_name TEXT NOT NULL,
  acres NUMERIC NOT NULL,
  planted_date DATE NOT NULL,
  status TEXT DEFAULT 'growing',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. Farm Expenses
CREATE TABLE IF NOT EXISTS farm_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  crop_id BIGINT REFERENCES farm_crops(id),
  item TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  category TEXT CHECK (category IN ('Seeds', 'Fertilizer', 'Pesticide', 'Labor', 'Equipment', 'Other')),
  expense_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. Community Posts
CREATE TABLE IF NOT EXISTS community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  author_name TEXT,
  author_location TEXT,
  content TEXT NOT NULL,
  post_type TEXT CHECK (post_type IN ('tip', 'question', 'success')) DEFAULT 'tip',
  likes INTEGER DEFAULT 0,
  tags TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. Post Likes (to prevent duplicate likes)
CREATE TABLE IF NOT EXISTS post_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES community_posts(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  UNIQUE(post_id, user_id)
);

-- 9. Notifications / Reminders
CREATE TABLE IF NOT EXISTS reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  title TEXT NOT NULL,
  note TEXT,
  due_date DATE,
  urgency TEXT CHECK (urgency IN ('high', 'medium', 'upcoming')) DEFAULT 'upcoming',
  done BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 10. Market Price Cache
CREATE TABLE IF NOT EXISTS market_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crop_name TEXT NOT NULL,
  price NUMERIC,
  unit TEXT,
  market TEXT,
  change_pct NUMERIC,
  decision TEXT CHECK (decision IN ('sell', 'hold', 'wait')),
  forecast TEXT,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE farm_crops ENABLE ROW LEVEL SECURITY;
ALTER TABLE farm_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "profile_select" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profile_insert" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profile_update" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Scans policies
CREATE POLICY "scans_all" ON scans FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Orders policies
CREATE POLICY "orders_all" ON orders FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Farm crops policies
CREATE POLICY "farm_crops_all" ON farm_crops FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Farm expenses policies
CREATE POLICY "farm_expenses_all" ON farm_expenses FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Community posts — public read, own write
CREATE POLICY "posts_select" ON community_posts FOR SELECT USING (true);
CREATE POLICY "posts_insert" ON community_posts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "posts_update" ON community_posts FOR UPDATE USING (auth.uid() = user_id);

-- Post likes
CREATE POLICY "likes_all" ON post_likes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Products — public read
CREATE POLICY "products_read" ON products FOR SELECT USING (true);

-- Reminders
CREATE POLICY "reminders_all" ON reminders FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- SEED SAMPLE PRODUCTS
-- ============================================================
INSERT INTO products (name, category, price, unit, stock, seller, description, rating, tag) VALUES
('NPK Fertilizer 19:19:19', 'Fertilizer', 980, '50kg bag', 45, 'Krishi Kendra, Nashik', 'Balanced nutrition for all crop stages', 4.8, 'Best for Tomato'),
('Mancozeb 75% WP', 'Pesticide', 340, '500g pack', 20, 'Agro Shop, 2km away', 'Broad spectrum fungicide — early blight, downy mildew', 4.6, 'Disease control'),
('Neem Oil Spray 1500 PPM', 'Pesticide', 220, '1L bottle', 30, 'Organic Farm Store', 'Natural pest control, safe for beneficial insects', 4.5, 'Organic'),
('Tomato Hybrid Seeds (Arka Rakshak)', 'Seeds', 550, '10g pack', 15, 'IIHR Certified Dealer', 'Disease resistant, 18-22 t/acre yield', 4.9, 'High yield'),
('Urea (46% N) - Subsidized', 'Fertilizer', 267, '50kg bag', 200, 'Government Depot', 'Quick nitrogen boost for vegetative stage', 4.4, 'Subsidized'),
('Onion Seeds Bhima Raj', 'Seeds', 480, '500g pack', 12, 'DOGR Certified', 'High bulb weight, Kharif and Rabi suitable', 4.8, 'Best Seller'),
('Drip Irrigation Kit', 'Equipment', 4500, 'per acre kit', 8, 'Jain Irrigation', 'Complete drip kit — pipes, drippers, filter, timer', 4.7, 'Water saving'),
('Chlorpyrifos 20 EC', 'Pesticide', 380, '500ml bottle', 25, 'Agro Point, 4km', 'For aphids, thrips, bollworms', 4.3, 'Broad spectrum')
ON CONFLICT DO NOTHING;
